language: cpp
sudo: required
dist: trusty
before_install:
 - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu/ wily main universe' -y
 - |
   sudo sh -c '/bin/echo -e "Package: *\nPin: release n=wily\nPin-Priority: 1" > /etc/apt/preferences.d/wily'
 - sudo apt-get update -qq
install:
 - sudo ./prepare-release travis-ci
 - sudo apt-get -qq -y -t wily install gettext liblz4-dev
 - make
script:
 - make test
 - ./test/integration/run-tests -q
 - sudo adduser --force-badname --system --home /nonexistent --no-create-home --quiet _apt || true
 - sudo ./test/integration/run-tests -q

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VrmE21W4ciFupWp4v83rK/YdEfy7wBygBsYU6rITLmYcVUkf34ZPf7FScrl/UTAE7bc4F64jRQ3nf9KnxHcknnlFRWoJ3WXW0mOM8amCvVw7Lp473+63RPPGKh24n4Fw0n0HdQ3DuhUAFTrYbJ4bSJcc7hswdz8lb57XG5dp7Ss="

addons:
  coverity_scan:
    project:
      name: "Debian/apt"
      description: "Build submitted via Travis CI"
    notification_email: jak@jak-linux.org
    build_command_prepend: "make startup"
    build_command:   "make"
    branch_pattern: coverity_scan
